name: card_matching_game
description: "An exciting Flutter card-matching game with animations, sound effects, and enhanced UI."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # UI and Animation Enhancements
  confetti: ^0.8.0            # Victory confetti effect
  audioplayers: ^6.3.0        # For sound effects (click, match, victory)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Sound Effects for Enhanced Gameplay
  assets:
    - assets/sounds/click.mp3
    - assets/sounds/match.mp3
    - assets/sounds/victory.mp3
