name: card_matching_game
description: "Card Matching Game with local DB, scoreboard, custom matches, and enhanced UI."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.8
  path: ^1.9.0
  confetti: ^0.8.0
  audioplayers: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/back.JPG
    - assets/images/bob.JPG
    - assets/images/kaaju.JPG
    - assets/images/raju.JPG
    - assets/images/sweety.JPG
    - assets/sounds/click.mp3
    - assets/sounds/match.mp3
    - assets/sounds/victory.mp3
