name: card_matching_game
description: "A feature-rich, animated Flutter card-matching game with enhanced UI, leaderboard, pause/resume, and dark/light mode."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # UI Enhancements
  cupertino_icons: ^1.0.8
  confetti: ^0.8.0            # Victory celebration effect
  audioplayers: ^6.3.0        # Sound effects for card flip, match, and victory
  vibration: ^3.1.3           # Device vibration for haptic feedback
  provider: ^6.1.2            # State management for better UI flow

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Image Assets (Using URLs instead of Local Assets)
  assets:
    - assets/images/       # Add this if you wish to add future local assets

  # Fonts for UI Improvement
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
